name: Issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  help-wanted:
    uses: laravel/.github/.github/workflows/issues.yml@41cb33d868e3f67ea2c9bb53f1ebd9a379400f63 # main
